object versions {

  val fs2                = "2.2.2"
  val newtype            = "0.4.3"
  val monix              = "3.1.0"
  val tofu               = "0.8.0"
  val catsVersion        = "2.2.0"
  val catsEffectVersion  = "2.3.0"
  val catsMtlVersion     = "0.7.0"
  val catsMeowMtl        = "0.4.0"
  val catsTaglessVersion = "0.12"
  val mouseVersion       = "0.23"
  val manatki            = "0.10.1"
  val manatkiCirce       = "0.11.6"
  val manatkiPureConfig  = "0.11.6"
  val pureConfigVersion  = "0.12.1"
  val scopt              = "4.0.0"
  val log4Cats           = "0.3.0"
  val logback            = "1.2.3"
  val circeFs2           = "0.13.0"
  val slf4j              = "1.7.25"
  val scodec             = "1.11.7"
  val scodecStream       = "2.0.0"
  val xml                = "2.0.0-M3"
  val bc                 = "1.68"

  val KindProjector = "0.11.0"
  val MacroParadise = "2.1.1"
}
